import axios from 'axios';
const API = axios.create({ baseURL: import.meta.env.VITE_API_URL || 'http://localhost:3000' });
export const getLeads            = (p)    => API.get('/api/leads', { params:p });
export const getLead             = (id)   => API.get(`/api/leads/${id}`);
export const getLeadConversation = (id)   => API.get(`/api/leads/${id}/conversation`);
export const updateLead          = (id,d) => API.put(`/api/leads/${id}`, d);
export const addNote             = (id,n) => API.post(`/api/leads/${id}/notes`, { note:n });
export const exportLeads         = (p)    => API.get('/api/leads/export', { params:p, responseType:'blob' });
export const getCampaigns        = ()     => API.get('/api/campaigns');
export const createCampaign      = (d)    => API.post('/api/campaigns', d);
export const launchCampaign      = (id)   => API.post(`/api/campaigns/${id}/launch`);
export const pauseCampaign       = (id)   => API.put(`/api/campaigns/${id}/pause`);
export const getCampaignReport   = (id)   => API.get(`/api/tracking/campaigns/${id}`);
export const getOverview         = ()     => API.get('/api/analytics/overview');
export const getFunnel           = ()     => API.get('/api/analytics/funnel');
export const getGrowth           = (days) => API.get(`/api/analytics/growth?days=${days}`);
export const getTrackingDashboard= ()     => API.get('/api/tracking/dashboard');
export const getAutomations      = ()     => API.get('/api/automations');
export const createAutomation    = (d)    => API.post('/api/automations', d);
export default API;